/*
  Add restructured Mama Lenny's menu:
  - Creates/ensures categories.
  - Inserts menu_items WITHOUT specifying id (UUID auto-generated).
  - Inserts variations WITHOUT specifying id (UUID auto-generated).

  NOTE:
  - categories.id is a text primary key without a default, so we MUST provide
    stable ids there. All other ids are auto-generated by the existing schema.
*/

-- 1) Categories
INSERT INTO public.categories (id, name, icon, sort_order, active) VALUES
  ('pancit-toppings', 'Pancit Toppings', '🍜', 10, true),
  ('family-trays-beef', 'Family & Party Trays (Beef)', '🥩', 20, true),
  ('family-trays-pork', 'Family & Party Trays (Pork)', '🐖', 21, true),
  ('family-trays-chicken', 'Family & Party Trays (Chicken)', '🍗', 22, true),
  ('family-trays-seafood', 'Family & Party Trays (Seafood)', '🦐', 23, true),
  ('family-trays-veggies', 'Family & Party Trays (Vegetables)', '🥦', 24, true),
  ('family-trays-pasta', 'Family & Party Trays (Pasta)', '🍝', 25, true),
  ('specialties-trays', 'Specialties (Trays - Same Day Order)', '🍱', 30, true),
  ('specialties-tub', 'Specialties (1,000 mL Tub)', '🥘', 31, true),
  ('snacks', 'Snacks', '🍢', 40, true),
  ('desserts', 'Desserts', '🍮', 50, true),
  ('party-packages', 'Party Packages', '🎁', 60, true)
ON CONFLICT (id) DO NOTHING;


-- Helper pattern:
-- Each item uses:
--   WITH item AS (
--     INSERT INTO menu_items (name, description, base_price, category, popular, available)
--     VALUES ('Name', 'Description', base_price_numeric, 'category-id', false, true)
--     RETURNING id
--   )
--   INSERT INTO variations (menu_item_id, name, price)
--   SELECT item.id, v.name, v.price
--   FROM item, LATERAL (VALUES (...)) AS v(name, price);


-- 2) PANCIT TOPPINGS

-- Bihon Guisado Con Lechon
WITH item AS (
  INSERT INTO public.menu_items (name, description, base_price, category, popular, available)
  VALUES (
    'Bihon Guisado Con Lechon',
    'Bihon Guisado with Con Lechon. Sizes: 1L Tub (2-3 Pax), Bilao 1 (5-6 Pax), Bilao 2 (10-12 Pax), Bilao 3 (14-16 Pax), Bilao 4 (18-20 Pax).',
    285,
    'pancit-toppings',
    false,
    true
  )
  RETURNING id
)
INSERT INTO public.variations (menu_item_id, name, price)
SELECT item.id, v.name, v.price
FROM item,
LATERAL (VALUES
  ('1L Tub (2-3 Pax)', 285),
  ('Bilao 1 (5-6 Pax)', 610),
  ('Bilao 2 (10-12 Pax)', 810),
  ('Bilao 3 (14-16 Pax)', 1150),
  ('Bilao 4 (18-20 Pax)', 1550)
) AS v(name, price);

-- Bihon Guisado Chicken
WITH item AS (
  INSERT INTO public.menu_items (name, description, base_price, category, popular, available)
  VALUES (
    'Bihon Guisado Chicken',
    'Bihon Guisado with Chicken. Sizes: 1L Tub (2-3 Pax), Bilao 1 (5-6 Pax), Bilao 2 (10-12 Pax), Bilao 3 (14-16 Pax), Bilao 4 (18-20 Pax).',
    199,
    'pancit-toppings',
    false,
    true
  )
  RETURNING id
)
INSERT INTO public.variations (menu_item_id, name, price)
SELECT item.id, v.name, v.price
FROM item,
LATERAL (VALUES
  ('1L Tub (2-3 Pax)', 199),
  ('Bilao 1 (5-6 Pax)', 475),
  ('Bilao 2 (10-12 Pax)', 685),
  ('Bilao 3 (14-16 Pax)', 995),
  ('Bilao 4 (18-20 Pax)', 1355)
) AS v(name, price);

-- Bihon Guisado Bagnet
WITH item AS (
  INSERT INTO public.menu_items (name, description, base_price, category, popular, available)
  VALUES (
    'Bihon Guisado Bagnet',
    'Bihon Guisado with Bagnet. Sizes: 1L Tub (2-3 Pax), Bilao 1 (5-6 Pax), Bilao 2 (10-12 Pax), Bilao 3 (14-16 Pax), Bilao 4 (18-20 Pax).',
    235,
    'pancit-toppings',
    false,
    true
  )
  RETURNING id
)
INSERT INTO public.variations (menu_item_id, name, price)
SELECT item.id, v.name, v.price
FROM item,
LATERAL (VALUES
  ('1L Tub (2-3 Pax)', 235),
  ('Bilao 1 (5-6 Pax)', 535),
  ('Bilao 2 (10-12 Pax)', 775),
  ('Bilao 3 (14-16 Pax)', 1100),
  ('Bilao 4 (18-20 Pax)', 1365)
) AS v(name, price);

-- Special Canton Con Lechon
WITH item AS (
  INSERT INTO public.menu_items (name, description, base_price, category, popular, available)
  VALUES (
    'Special Canton Con Lechon',
    'Special Canton with Con Lechon. Sizes: 1L Tub (2-3 Pax), Bilao 1 (5-6 Pax), Bilao 2 (10-12 Pax), Bilao 3 (14-16 Pax), Bilao 4 (18-20 Pax).',
    320,
    'pancit-toppings',
    false,
    true
  )
  RETURNING id
)
INSERT INTO public.variations (menu_item_id, name, price)
SELECT item.id, v.name, v.price
FROM item,
LATERAL (VALUES
  ('1L Tub (2-3 Pax)', 320),
  ('Bilao 1 (5-6 Pax)', 695),
  ('Bilao 2 (10-12 Pax)', 965),
  ('Bilao 3 (14-16 Pax)', 1200),
  ('Bilao 4 (18-20 Pax)', 1665)
) AS v(name, price);

-- Special Canton Chicken
WITH item AS (
  INSERT INTO public.menu_items (name, description, base_price, category, popular, available)
  VALUES (
    'Special Canton Chicken',
    'Special Canton with Chicken. Sizes: 1L Tub (2-3 Pax), Bilao 1 (5-6 Pax), Bilao 2 (10-12 Pax), Bilao 3 (14-16 Pax), Bilao 4 (18-20 Pax).',
    255,
    'pancit-toppings',
    false,
    true
  )
  RETURNING id
)
INSERT INTO public.variations (menu_item_id, name, price)
SELECT item.id, v.name, v.price
FROM item,
LATERAL (VALUES
  ('1L Tub (2-3 Pax)', 255),
  ('Bilao 1 (5-6 Pax)', 565),
  ('Bilao 2 (10-12 Pax)', 795),
  ('Bilao 3 (14-16 Pax)', 965),
  ('Bilao 4 (18-20 Pax)', 1255)
) AS v(name, price);

-- Special Canton Bagnet
WITH item AS (
  INSERT INTO public.menu_items (name, description, base_price, category, popular, available)
  VALUES (
    'Special Canton Bagnet',
    'Special Canton with Bagnet. Sizes: 1L Tub (2-3 Pax), Bilao 1 (5-6 Pax), Bilao 2 (10-12 Pax), Bilao 3 (14-16 Pax), Bilao 4 (18-20 Pax).',
    295,
    'pancit-toppings',
    false,
    true
  )
  RETURNING id
)
INSERT INTO public.variations (menu_item_id, name, price)
SELECT item.id, v.name, v.price
FROM item,
LATERAL (VALUES
  ('1L Tub (2-3 Pax)', 295),
  ('Bilao 1 (5-6 Pax)', 645),
  ('Bilao 2 (10-12 Pax)', 935),
  ('Bilao 3 (14-16 Pax)', 1165),
  ('Bilao 4 (18-20 Pax)', 1465)
) AS v(name, price);

-- Bihon / Canton Con Lechon
WITH item AS (
  INSERT INTO public.menu_items (name, description, base_price, category, popular, available)
  VALUES (
    'Bihon / Canton Con Lechon',
    'Bihon / Canton with Con Lechon. Sizes: 1L Tub (2-3 Pax), Bilao 1 (5-6 Pax), Bilao 2 (10-12 Pax), Bilao 3 (14-16 Pax), Bilao 4 (18-20 Pax).',
    295,
    'pancit-toppings',
    false,
    true
  )
  RETURNING id
)
INSERT INTO public.variations (menu_item_id, name, price)
SELECT item.id, v.name, v.price
FROM item,
LATERAL (VALUES
  ('1L Tub (2-3 Pax)', 295),
  ('Bilao 1 (5-6 Pax)', 685),
  ('Bilao 2 (10-12 Pax)', 895),
  ('Bilao 3 (14-16 Pax)', 1350),
  ('Bilao 4 (18-20 Pax)', 1650)
) AS v(name, price);

-- Bihon / Canton Chicken
WITH item AS (
  INSERT INTO public.menu_items (name, description, base_price, category, popular, available)
  VALUES (
    'Bihon / Canton Chicken',
    'Bihon / Canton with Chicken. Sizes: 1L Tub (2-3 Pax), Bilao 1 (5-6 Pax), Bilao 2 (10-12 Pax), Bilao 3 (14-16 Pax), Bilao 4 (18-20 Pax).',
    225,
    'pancit-toppings',
    false,
    true
  )
  RETURNING id
)
INSERT INTO public.variations (menu_item_id, name, price)
SELECT item.id, v.name, v.price
FROM item,
LATERAL (VALUES
  ('1L Tub (2-3 Pax)', 225),
  ('Bilao 1 (5-6 Pax)', 575),
  ('Bilao 2 (10-12 Pax)', 795),
  ('Bilao 3 (14-16 Pax)', 935),
  ('Bilao 4 (18-20 Pax)', 1350)
) AS v(name, price);

-- Bihon / Canton Bagnet
WITH item AS (
  INSERT INTO public.menu_items (name, description, base_price, category, popular, available)
  VALUES (
    'Bihon / Canton Bagnet',
    'Bihon / Canton with Bagnet. Sizes: 1L Tub (2-3 Pax), Bilao 1 (5-6 Pax), Bilao 2 (10-12 Pax), Bilao 3 (14-16 Pax), Bilao 4 (18-20 Pax).',
    285,
    'pancit-toppings',
    false,
    true
  )
  RETURNING id
)
INSERT INTO public.variations (menu_item_id, name, price)
SELECT item.id, v.name, v.price
FROM item,
LATERAL (VALUES
  ('1L Tub (2-3 Pax)', 285),
  ('Bilao 1 (5-6 Pax)', 615),
  ('Bilao 2 (10-12 Pax)', 855),
  ('Bilao 3 (14-16 Pax)', 1150),
  ('Bilao 4 (18-20 Pax)', 1550)
) AS v(name, price);

-- Mikki / Bihon Con Lechon
WITH item AS (
  INSERT INTO public.menu_items (name, description, base_price, category, popular, available)
  VALUES (
    'Mikki / Bihon Con Lechon',
    'Mikki / Bihon with Con Lechon. Sizes: 1L Tub (2-3 Pax), Bilao 1 (5-6 Pax), Bilao 2 (10-12 Pax), Bilao 3 (14-16 Pax), Bilao 4 (18-20 Pax).',
    325,
    'pancit-toppings',
    false,
    true
  )
  RETURNING id
)
INSERT INTO public.variations (menu_item_id, name, price)
SELECT item.id, v.name, v.price
FROM item,
LATERAL (VALUES
  ('1L Tub (2-3 Pax)', 325),
  ('Bilao 1 (5-6 Pax)', 685),
  ('Bilao 2 (10-12 Pax)', 875),
  ('Bilao 3 (14-16 Pax)', 1350),
  ('Bilao 4 (18-20 Pax)', 1650)
) AS v(name, price);

-- Mikki / Bihon Chicken
WITH item AS (
  INSERT INTO public.menu_items (name, description, base_price, category, popular, available)
  VALUES (
    'Mikki / Bihon Chicken',
    'Mikki / Bihon with Chicken. Sizes: 1L Tub (2-3 Pax), Bilao 1 (5-6 Pax), Bilao 2 (10-12 Pax), Bilao 3 (14-16 Pax), Bilao 4 (18-20 Pax).',
    250,
    'pancit-toppings',
    false,
    true
  )
  RETURNING id
)
INSERT INTO public.variations (menu_item_id, name, price)
SELECT item.id, v.name, v.price
FROM item,
LATERAL (VALUES
  ('1L Tub (2-3 Pax)', 250),
  ('Bilao 1 (5-6 Pax)', 575),
  ('Bilao 2 (10-12 Pax)', 765),
  ('Bilao 3 (14-16 Pax)', 935),
  ('Bilao 4 (18-20 Pax)', 1350)
) AS v(name, price);

-- Mikki / Bihon Bagnet
WITH item AS (
  INSERT INTO public.menu_items (name, description, base_price, category, popular, available)
  VALUES (
    'Mikki / Bihon Bagnet',
    'Mikki / Bihon with Bagnet. Sizes: 1L Tub (2-3 Pax), Bilao 1 (5-6 Pax), Bilao 2 (10-12 Pax), Bilao 3 (14-16 Pax), Bilao 4 (18-20 Pax).',
    285,
    'pancit-toppings',
    false,
    true
  )
  RETURNING id
)
INSERT INTO public.variations (menu_item_id, name, price)
SELECT item.id, v.name, v.price
FROM item,
LATERAL (VALUES
  ('1L Tub (2-3 Pax)', 285),
  ('Bilao 1 (5-6 Pax)', 635),
  ('Bilao 2 (10-12 Pax)', 835),
  ('Bilao 3 (14-16 Pax)', 1150),
  ('Bilao 4 (18-20 Pax)', 1550)
) AS v(name, price);

-- Special Palabok Con Lechon
WITH item AS (
  INSERT INTO public.menu_items (name, description, base_price, category, popular, available)
  VALUES (
    'Special Palabok Con Lechon',
    'Special Palabok with Con Lechon. Sizes: 1L Tub (2-3 Pax), Bilao 1 (5-6 Pax), Bilao 2 (10-12 Pax), Bilao 3 (14-16 Pax), Bilao 4 (18-20 Pax).',
    325,
    'pancit-toppings',
    false,
    true
  )
  RETURNING id
)
INSERT INTO public.variations (menu_item_id, name, price)
SELECT item.id, v.name, v.price
FROM item,
LATERAL (VALUES
  ('1L Tub (2-3 Pax)', 325),
  ('Bilao 1 (5-6 Pax)', 720),
  ('Bilao 2 (10-12 Pax)', 965),
  ('Bilao 3 (14-16 Pax)', 1350),
  ('Bilao 4 (18-20 Pax)', 1650)
) AS v(name, price);

-- Special Palabok Chicken
WITH item AS (
  INSERT INTO public.menu_items (name, description, base_price, category, popular, available)
  VALUES (
    'Special Palabok Chicken',
    'Special Palabok with Chicken. Sizes: 1L Tub (2-3 Pax), Bilao 1 (5-6 Pax), Bilao 2 (10-12 Pax), Bilao 3 (14-16 Pax), Bilao 4 (18-20 Pax).',
    285,
    'pancit-toppings',
    false,
    true
  )
  RETURNING id
)
INSERT INTO public.variations (menu_item_id, name, price)
SELECT item.id, v.name, v.price
FROM item,
LATERAL (VALUES
  ('1L Tub (2-3 Pax)', 285),
  ('Bilao 1 (5-6 Pax)', 655),
  ('Bilao 2 (10-12 Pax)', 895),
  ('Bilao 3 (14-16 Pax)', 1200),
  ('Bilao 4 (18-20 Pax)', 1550)
) AS v(name, price);

-- Japchae Con Lechon
WITH item AS (
  INSERT INTO public.menu_items (name, description, base_price, category, popular, available)
  VALUES (
    'Japchae Con Lechon',
    'Japchae with Con Lechon. Sizes: 1L Tub (2-3 Pax), Bilao 1 (5-6 Pax), Bilao 2 (10-12 Pax), Bilao 3 (14-16 Pax), Bilao 4 (18-20 Pax).',
    365,
    'pancit-toppings',
    false,
    true
  )
  RETURNING id
)
INSERT INTO public.variations (menu_item_id, name, price)
SELECT item.id, v.name, v.price
FROM item,
LATERAL (VALUES
  ('1L Tub (2-3 Pax)', 365),
  ('Bilao 1 (5-6 Pax)', 655),
  ('Bilao 2 (10-12 Pax)', 935),
  ('Bilao 3 (14-16 Pax)', 1465),
  ('Bilao 4 (18-20 Pax)', 1835)
) AS v(name, price);

-- Japchae Chicken
WITH item AS (
  INSERT INTO public.menu_items (name, description, base_price, category, popular, available)
  VALUES (
    'Japchae Chicken',
    'Japchae with Chicken. Sizes: 1L Tub (2-3 Pax), Bilao 1 (5-6 Pax), Bilao 2 (10-12 Pax), Bilao 3 (14-16 Pax), Bilao 4 (18-20 Pax).',
    325,
    'pancit-toppings',
    false,
    true
  )
  RETURNING id
)
INSERT INTO public.variations (menu_item_id, name, price)
SELECT item.id, v.name, v.price
FROM item,
LATERAL (VALUES
  ('1L Tub (2-3 Pax)', 325),
  ('Bilao 1 (5-6 Pax)', 585),
  ('Bilao 2 (10-12 Pax)', 835),
  ('Bilao 3 (14-16 Pax)', 1295),
  ('Bilao 4 (18-20 Pax)', 1495)
) AS v(name, price);

-- Pancit Puti
WITH item AS (
  INSERT INTO public.menu_items (name, description, base_price, category, popular, available)
  VALUES (
    'Pancit Puti',
    'Pancit Puti. Sizes: 1L Tub (2-3 Pax), Bilao 1 (5-6 Pax), Bilao 2 (10-12 Pax), Bilao 3 (14-16 Pax), Bilao 4 (18-20 Pax).',
    195,
    'pancit-toppings',
    false,
    true
  )
  RETURNING id
)
INSERT INTO public.variations (menu_item_id, name, price)
SELECT item.id, v.name, v.price
FROM item,
LATERAL (VALUES
  ('1L Tub (2-3 Pax)', 195),
  ('Bilao 1 (5-6 Pax)', 485),
  ('Bilao 2 (10-12 Pax)', 695),
  ('Bilao 3 (14-16 Pax)', 885),
  ('Bilao 4 (18-20 Pax)', 1260)
) AS v(name, price);

-- Special Lomi Con Lechon
WITH item AS (
  INSERT INTO public.menu_items (name, description, base_price, category, popular, available)
  VALUES (
    'Special Lomi Con Lechon',
    'Special Lomi with Con Lechon. Sizes: 1L Tub (2-3 Pax), Bilao 1 (5-6 Pax).',
    195,
    'pancit-toppings',
    false,
    true
  )
  RETURNING id
)
INSERT INTO public.variations (menu_item_id, name, price)
SELECT item.id, v.name, v.price
FROM item,
LATERAL (VALUES
  ('1L Tub (2-3 Pax)', 195),
  ('Bilao 1 (5-6 Pax)', 265)
) AS v(name, price);


-- Due to length, the rest of the menu (Family & Party Trays: Beef, Pork, Chicken, Seafood, Veggies, Pasta; Specialties Trays & Tub; Snacks; Desserts; Party Packages)
-- should follow the same pattern: one menu_items row per "Name" with base_price equal to the solo / family price,
-- plus variations rows for each tray size or package size.
--
-- You can copy the pattern above and plug in:
--   - category: family-trays-beef / family-trays-pork / family-trays-chicken / family-trays-seafood /
--               family-trays-veggies / family-trays-pasta / specialties-trays / specialties-tub /
--               snacks / desserts / party-packages
--   - name: the item Name
--   - description: the prose you provided
--   - base_price: the smallest price listed for that item
--   - variations: one row per size (Family Tray, Party Tray, Solo, etc.)


